### ISSUE TITLE
LogentriesError: Buffer is full, unable to log

### ISSUE THREAD

**Issue by dev0x10** [logentries/le_node#102]
Last night my server had error that caused by Logentries library.
I haven't tried to trace what is the main cause but this is a bit information from my console

```
LogentriesError: Buffer is full, unable to log: "{"userAgent":"Mozilla/5.0 ...".
proxy-1 (err):     at Logger.log (/home/user/node_modules/le_node/lib/node_modules/logger.js:376:24)
proxy-1 (err):     at Logger.value [as info] (/home/user/node_modules/le_node/lib/node_modules/logger.js:171:16)
proxy-1 (err):     at null.<anonymous> (/home/user/plugins/leLogger.js:32:14)
proxy-1 (err):     at emitOne (events.js:77:13)
proxy-1 (err):     at emit (events.js:169:7)
proxy-1 (err):     at handler (/home/user/node_modules/hapi/node_modules/kilt/lib/index.js:56:44)
```

If someone had the same problem, could you give me information about this? 
Thanks!!

**Comment by bathos** [comment]
The default buffer size is 100 (entries). If you have a huge throughput, you may want to raise the buffer size (`opts.bufferSize`). But in many cases filling the buffer this would suggest something is amiss -- like accidentally calling a log method repeatedly in a synchronous loop.

**Comment by dev0x10** [comment]
Hmm I may have to check some part of my codes.
But this only happened last night after our new server running for almost 3 weeks.
Anyway thanks for the information!

I'm still waiting for other comment, I will close this within two days if no one comment anymore.

**Comment by bathos** [comment]
If it happened after three weeks running without problems, although it doesn't rule anything out particularly, it does suggest what happened was (given your logs appear to be for http requests) most likely caused by a big traffic spike or network problems. The error is emitted so that you don't silently lose log entries under such circumstances; I suppose I'd suggest you fallback to stderr or something, since by its nature, you can't (at least not immediately) log the error to the le client itself.

**Comment by yauri** [comment]
I guess it caused by big traffic spike.
Thanks!
Case closed

**Comment by dev0x10** [comment]
I guess it caused by big traffic spike.
Thanks!
Case closed
