### ISSUE TITLE
Error After Upgrade To Node 6.x

### ISSUE THREAD

**Issue by dev0x10** [logentries/le_node#106]
Got error after upgrading to Node 6. I'm using "le_node": "^1.3.0"

`160430/043456.583, [error], message: Uncaught error: Cannot convert object to primitive value stack: TypeError: Uncaught error: Cannot convert object to primitive value
    at Socket.<anonymous> (/Users/username/projectname/node_modules/le_node/lib/node_modules/serialize.js:70:9)
    at Socket.<anonymous> (/Users/username/projectname/node_modules/le_node/node_modules/lodash/index.js:3337:35)
    at Socket.<anonymous> (/Users/username/projectname/node_modules/le_node/node_modules/json-stringify-safe/stringify.js:25:48)
    at Object.stringify (native)
    at Logger.stringify (/Users/username/projectname/node_modules/le_node/node_modules/json-stringify-safe/stringify.js:5:15)
    at Logger.wrapper (/Users/username/projectname/node_modules/le_node/node_modules/lodash/index.js:3543:19)
    at Logger.log (/Users/username/projectname/node_modules/le_node/lib/node_modules/logger.js:428:28)`

The problem is serialize.js line 70
```javascript
if (1 / val === -Infinity) return '-0';
```
I did try catch and found that if the 'val' is a circular object then it will causing error.
I don't really understand completely why it needs to do 1/val

**Comment by bathos** [comment]
Interesting. Is Node 6 the definite factor here? Circular refs (should) just get turned into a string that says as much. This check is part of the serialization function -- it permits the preservation of negative zero, which is lost in a default JSON.stringify. Realistically it's very unimportant and was just included since the goal was to lose as little data as possible and it's a cheap one to confirm, but removing it may not actually solve your problem given some of the other checks.

For that to throw, however, the object in question couldn't be any normal object. Open your browser console and you can confirm, `1 / {}` will not throw. To cause a primitive conversion error you'd generally need to be either logging an exotic host object or an object which was deliberately constructed to not inherit from Object. If that's the case, then the question is: What should an object serializer do when it encounters an exotic entity that is neither primitive nor an instance of Object? I agree it shouldn't throw, but I'm thinking it also should probably ignore it entirely.

Can you say more about the object that it fails with?

**Comment by dev0x10** [comment]
I'm testing the same code on Node 5 and it has no problem, but honestly I'm not 100% sure if upgrading to Node 6 is the root problem.
So I put try catch on that line
```javascript
		try {
			if (1 / val === -Infinity) return '-0';
		}
		catch(e) {
			console.log('catch', val);
			return '-0';
		}
```

And here is some of the catch result
```javascript
catch { connection: [ [Function: connectionListener], [Function] ],
  removeListener: [Function: onRemoveListener],
  request: [ [Function], [Function] ],
  clientError: [Function] }

catch { finish:
   [ [Function: resOnFinish],
     { [Function: g] listener: [Function] },
     [Function] ] }

catch { end:
   [ { [Function: g] listener: [Function: onend] },
     [Function: socketOnEnd] ],
  finish: [Function: onSocketFinish],
  _socketEnd: [Function: onSocketEnd],
  data: [ [Function], [Function: socketOnData] ],
  drain: [ [Function: ondrain], [Function: socketOnDrain] ],
  timeout: [Function],
  error: [Function: socketOnError],
  close:
   [ [Function: serverSocketCloseListener],
     { [Function: g] listener: [Function] },
     [Function: onServerResponseClose] ],
  resume: [Function: onSocketResume],
  pause: [Function: onSocketPause] }

catch { connection: [ [Function: connectionListener], [Function] ],
  removeListener: [Function: onRemoveListener],
  request: [ [Function], [Function] ],
  clientError: [Function] }
```

**Comment by bathos** [comment]
Great, that helps, all three of those objects are instances of EventEmitter. The Node 6 changelog does indeed list this in its [breaking changes](https://github.com/nodejs/node/wiki/Breaking-changes-between-v5-and-v6):

> The internal event handler storage object EventEmitter#_events now inherits from Object.create(null) rather than Object.prototype.

Breaking change indeed! So that explains it. The serializer actually does have a check for non-Object objects, but didn't consider objects that *inherit* from non-Object objects:

		// Prototypeless object
		if (_.isObject(val) && !Object.getPrototypeOf(val))
			return val;

That can be remedied by changing the second condition to `instanceof Object`. Which might be enough to solve it in your case, though I'm not sure if the circular reference handler will then choke on these particular objects, too.

**Comment by dev0x10** [comment]
Thanks for your time looking into the problem. I had another front-end project breaks because of Node 6.
I just put a new check condition following your suggestion and it works.
Should I send a PR or you will release the fix soon?

**Comment by bathos** [comment]
PR would be awesome, @dev0x10. I haven't had much free time for this project (despite the tag, I'm not an LE employee) so these days I mostly just field questions here when I can and confirm whether PRs seem legit.

**Comment by dev0x10** [comment]
@bathos Ah I see, I thought you were LE employee. 
Thanks for merging 👍

**Comment by bathos** [comment]
I used to be -- I wrote this client while I was there for my own usage, to address some bugs in the then-official client, and then it became the new official client. It could use some love -- even though it solved the more obvious issues in the original, it still has some problems with connection management, and at the time I had only been using ES6 for a few months and was still experimenting with new patterns, so the code makes some odd choices I probably wouldn't stand by today.

Thanks for the patch, merged & published.
