### ISSUE TITLE
Winston transport is failing to serialize objects

### ISSUE THREAD

**Issue by richard-still-ft** [logentries/le_node#13]
When using winston like so:
winston.info({"foo":"bar"});

The following will appear in the logs:
"2013-03-21T11:48:00.887Z" "info" "[object Object]"

**Comment by arieljake** [comment]
@alexgorbatchev in your fork, why did you take out the flatten option?

**Comment by alexgorbatchev** [comment]
Think it's still there https://github.com/alexgorbatchev/logentries/blob/master/lib/logentries.js#L142

**Comment by bathos** [comment]
Alex's fork is off of le_node 0.1.4, which had a flatten option but seemingly didn't document it. However I don't think it behaved quite the same as the flatten option that's in the current le_node codebase if that's what you mean.

**Comment by voitau** [comment]
Same issue for me. Since it is closed, what is the resolution?

**Comment by bathos** [comment]
So continuing here, voitau ... this issue, along with about a dozen others, was closed mainly because le_node 1+ isn't really the same application as prior versions. That is, I'd developed it independently and it ended up being the replacement. As such the examples, errors, etc, in outstanding issues were no longer applicable and (odds were) neither were the issues themselves. So it's just a coincidence that we ran into the same problem.

Both Winston and le_node are able to serialize objects into strings, and both do more than simple JSON.stringify, so that (for example) errors get serialized correctly. I'm not sure though whether winston is passing the serialized version or the original version to the transport. This is probably something simple that just comes from me not having an accurate model for how Winston communicates with the transport -- I'll try to sort it out over the weekend.

**Comment by goncaloneves** [comment]
Hi,

I solved this by stringifying winston meta object or changed line 687 of logger.js and removed toString method on meta:

`
if (_lodash2['default'].isString(msg)) msg += ' ' + this[$Logger][$serialize](meta.toString());else if (_lodash2['default'].isObject(msg)) msg[getSafeProp(msg, 'meta')] = meta;
`

to

`
if (_lodash2['default'].isString(msg)) msg += ' ' + this[$Logger][$serialize](meta);else if (_lodash2['default'].isObject(msg)) msg[getSafeProp(msg, 'meta')] = meta;
`

Hope it helps.

**Comment by bathos** [comment]
Thanks, it helps a great deal. That 'toString' was unambiguously an error -- but I'd never noticed since I didn't have any tests where winston made use of the meta param (I wasn't sure when it was ever used, or how, really). Given the nature of the error, it seems all the more odd that this bug manifested in both codebases. Fix forthcoming.

**Comment by voitau** [comment]
Just confirmed that is works as expected. Thanks for the quick resolution!

**Comment by goncaloneves** [comment]
Cool bathos, thanks for the release.
