### ISSUE TITLE
Colours?

### ISSUE THREAD

**Issue by mjmasn** [logentries/le_node#38]
Winston's console transport supports a colorize option, would be nice to have the same for the LogEntries transport seeing as colours *are* technically supported on the LogEntries platform.

**Comment by StephenHynes7** [comment]
We could do something for this, my only issue with promoting it however is that it can make searching in Logentries a pain since the encoding interferes with your searching capabilities e.g If "Hello" is encoded green and I do a search in Logentries for "Hello" chances are it won't come up since I haven't included the encodings.

**Comment by mjmasn** [comment]
Ah ok, that makes sense. I had tried adding encodings before but couldn't get it to display properly - assumed I was doing something wrong. I guess tagging is probably a better option then - I just wanted a visual way to quickly distinguish different log levels and other important info.

**Comment by bathos** [comment]
Unless the impact use of control characters currently has on text searchability changes, I think this one's out.
