### ISSUE TITLE
Execution hangs randomly

### ISSUE THREAD

**Issue by clicktravel-martindimitrov** [logentries/le_node#42]
Hi,

been using ```le_node``` recently and it looks like sometimes my script just freezes when it has to do some logging. 
A simple way to reproduce this problem is to have a script that only logs a single line and then run it a few times. 
I am using ```node``` v. 0.10.32 with the Nodeclipse plugin.

Thanks

**Comment by ptdixon** [comment]
Hi Martin,

Sorry for the delay. I will take a look and try to reproduce this problem...

**Comment by ptdixon** [comment]
Hi Martin,

Are you sure you are using logger.end() when you have finished logging. ? Otherwise the logger will keep the TCP socket open waiting for further events, and your node script will not exit. e.g.

  var le = require('le_node')
  var logger = le.logger({ token: 'YOUR_TOKEN' });
  logger.on('error',function(err){
    console.log('LOG ERROR: ', err);
  })
  ...
  logger.info('A simple log test...');
  ...
  logger.end();
  ...

(see examples/simple.js)

Hopefully this will solve your problem, but if not, please provide a detailed set of steps of how I can reproduce the issue.

Thanks for your patience,

Paul

**Comment by bathos** [comment]
No comparable issues have been reported with the new client to date. You would still need to call `closeConnection` or `end` as described above, but you shouldn't do so until you’re sure the transmission has taken place (listen for 'connection drain'). Given that, the above example would not **normally** hold the event loop open for longer than minimally needed.

That said, in cases like this where you wish to run a script that self-exits without using process to do so explicitly, there could be edge cases that keep the loop loopin’. For example, if establishing the network connection fails, it will begin an exponential backoff of retries. The timeouts involved will maintain the event loop just as an active connection would have. The client library will not have any way to know that it's suddenly the only code in the room still partying.

We could decorate `end` with additional behavior that cleans up any active timeouts. Which is a good idea -- it’s polite to clean up. That will reduce the odds of the self-exiting app staying open longer than desired, but I really don't think one should ever rely on that behavior. Any library that performs asynchronous operations is unlikely to have "event loop clearing" behavior that happens to coincide closely with the end time execution of other code. Many will even keep the loop open indefinitely by design. Shutdown in all but the most trivial node apps has to use process.exit() at some point: you do as much cleanup as you have control over and then pull the lever.
