### ISSUE TITLE
log-level not working with new Logger of winston

### ISSUE THREAD

**Issue by bendpx** [logentries/le_node#61]
I'm using this method to define a new transporter:
var logger = new winston.Logger({
    transports: [
        new winston.transports.Console({
            level: 'debug',
            handleExceptions: false,
            json: false,
            colorize: true
        }),
        new winston.transports.Logentries({
        options:{ level: 'warn'}, token: config.logEntriesToken
        })
    ],
    exitOnError: false
});

But the logentries transporter sends info and debug messages as well.

How come?

**Comment by bathos** [comment]
Looks like winston checks does a min level check on each transport before sending, but it expects a number:

https://github.com/winstonjs/winston/blob/master/lib/winston/logger.js#L184-L185

...and I'm pretty sure I'm giving it a name. Further, since Winston doesn't call the level-methods or supply the level-arg to `log`, the LE transport doesn't know what level Winston's message is and so it doesn't get caught at that point, either.

Fortunately this ought to be a really simple fix -- returning the level number to Winston.

**Comment by bathos** [comment]
Hm, hunch was wrong. We are returning a number to Winston there. I'll have to futz with this some more to understand what would cause that.

**Comment by bendpx** [comment]
Thanks, can you estimate when it fixed? we're trying to integrate with LE and all of our app are winston based.

**Comment by bathos** [comment]
I'd say Monday or Tuesday most likely. It'd be helpful to get a little more data in the meantime:

1. winston version
2. did you try setting the min level with a number, and if so, did the same thing happen?

**Comment by bendpx** [comment]
1. 1.0.0
2. which number mapped to what log level? I'll try

**Comment by bathos** [comment]
They're zero-indexed. Assuming you're using Winston's defaults, the number for 'warn' is 4:

https://github.com/winstonjs/winston/blob/master/lib/winston/config/npm-config.js#L11-L18

It's odd, actually -- I think they might have changed how the levels work at some point, because this isn't what I remember from a few months ago. But they do still expose these levels as 'levels' on the winston object (which is where the LE transport snatches them from) so that doesn't provide any obvious clue except that "something maybe changed."

**Comment by bathos** [comment]
I haven't had time to write a proper suite of tests for Winston features yet, but I'm pretty sure that little patch should solve this. It was actually something ridiculously simple/dumb and I was hunting for something weird and complex that did not exist.
