### ISSUE TITLE
logging an Error object raise empty message error

### ISSUE THREAD

**Issue by remkoboschker** [logentries/le_node#66]
The message is checked using lodash.isEmpty()

lodash.isEmtpy(new Error('whatever')) is true

therefore when I try to log an error, I get an error from le_node

Is this intentional? I would expect an error object to be logged without issues.

**Comment by bathos** [comment]
Yup, this is a mistake. The check shouldn't occur until after serialization, and it should just be to see if it's an empty string.

**Comment by bathos** [comment]
In addition to the empty check, the problem was compounded by our efforts to keep the original object unmutated by naive shallow cloning. Object.create isn’t an option given our needs so I've dealt with this by mutating (when timestamp or withLevel are true) and then deleting the added props at the end. Not ideal since technically this is still mutation (and would, for example, trigger Object.observe handlers) but I think the cases where this would matter are sufficiently unlikely.

**Comment by remkoboschker** [comment]
Thank you for the quick fix
