### ISSUE TITLE
Detecting Winston with npm 3

### ISSUE THREAD

**Issue by MartinKolarik** [logentries/le_node#67]
Since npm 3 installs, if possible, all modules to the top-level `node_modules` directory, the current method of automatically requiring Winston doesn't work very well. I've just run into a problem where one dependency of my dependency of my dependency... requires Winston, and I'm getting an error that the installed Winston version is unsupported by this module, although I didn't really install/enable Winston and have no intention of using it.

**Comment by bathos** [comment]
I don’t know much about what npm 3’s peer dependency changes mean yet, so I’m going to have to investigate this a bit to figure out the solution. I suspect the Codependency module isn’t compatible with npm3, but it also may not be necessary. The trouble is: how to make it work correctly with npm3 without breaking it for npm2 users, who still constitute the majority? hm

**Comment by MartinKolarik** [comment]
>I don’t know much about what npm 3’s peer dependency changes mean yet, so I’m going to have to investigate this a bit to figure out the solution.

Suppose you have a module A, which depends on module B, which depends on module C.

v2 would create the following directory structure:

```
node_modules
  - A
    - node_modules
      - B
        - node_modules
          - C
```

v3 creates this:

```
node_modules
  - A
  - B
  - C
```

... which means that any other module can require B and C with npm 3.

>The trouble is: how to make it work correctly with npm3 without breaking it for npm2 users, who still constitute the majority?

I think the best way would be to disable automatic registration with Winston, and let users call `.provisionWinston()` if they want to use it, but obviously, that's not backward compatible.

Another solution might be checking `package.json` to see if Winston is present in dependencies, and automatically registering if yes.

**Comment by bathos** [comment]
On further investigation I don’t see any reason npm3’s changes should prevent the current approach from working. This looks like a bug in Codependency -- and I’m guessing it could affect npm2 as well under the right circumstances -- because it’s not honoring the ‘optional’ setting when the module exists but is not in the target version range. There might be other settings I’m missing, but it seems the simplest solution is just to wildcard the optionalPeerDependency.

I could be wrong about that being the core issue, but that’s what it’s looking like to me. I’m not going to be able to set up an npm3 test immediately, but if you want to be the one to do the experiment, all it means is changing ~1.0.0 to * in package.json, and confirming whether the error still occurs, and if so, whether it’s the same one:

    "optionalPeerDependencies": {
      "winston": "~1.0.0"
    }

If that doesn’t address it, rolling a small replacement for Codependency that does the package.json check as you described in the last paragraph is probably the best solution that shouldn’t cause breaking changes.

**Comment by MartinKolarik** [comment]
>because it’s not honoring the ‘optional’ setting when the module exists but is not in the target version range

I suppose that depends on the definition of "optional". It's possible that the current behavior is intentional because they expect that if the module is there, user simply accidentally installed the wrong version.

>if you want to be the one to do the experiment, all it means is changing ~1.0.0 to * in package.json, and confirming whether the error still occurs

I *do think* this would fix it in some cases, but not in my case... In my case I have Winston v0.9, so I still don't meet the 1.x.x requirement.

**Comment by bathos** [comment]
It doesn’t really require 1, so that’s actually a mistake in itself. When I set the version I was thinking ~ meant ‘preferred’ rather than ‘1.x.x’ that I need to change regardless.

**Comment by MartinKolarik** [comment]
In that case, setting it to `x.x.x` might work. I'll test it later today.

**Comment by MartinKolarik** [comment]
Indeed, `x.x.x` solves this issue.

**Comment by bathos** [comment]
Updated in ver 1.0.11.

**Comment by MartinKolarik** [comment]
Thanks!
