### ISSUE TITLE
No logs being written: small node js program.

### ISSUE THREAD

**Issue by acrodrig** [logentries/le_node#75]
I am trying to make work this simple program, but it never works. Could you help?

```javascript
var Logger = require("le_node");
var log = new Logger({ token:"<token>" });

log.err("Testing logger with error!");

log.end();
```

**Comment by bathos** [comment]
The above appears valid; beyond confirming that, there's not enough information here to guess what's up. Does it throw?

**Comment by acrodrig** [comment]
No, it exits normally and no log entry is found. To reprpduce:

1. Create a new log
2. Run above program with new log token

**Comment by StephenHynes7** [comment]
If you have a sleep after the log.err are you able to see the logs? My guess the issue here is the asynchronous operation of forwarding logs to Logentries, if the main thread exits before the background thread finishes then that could explain why no log data is sent.

**Comment by bathos** [comment]
I didn't catch the `log.end()` bit the first time. That shuts everything down, and since it happens in the same tick as the write, no data will reach the connection. In fact I think it would be wise to tweak this a bit -- `end()` should probably kill the inner connection asynchronously, since it may not be obvious to users that, in cases like this, they can't write + kill it all at once.

**Comment by acrodrig** [comment]
Ok, so I presume that if this is closed the issue is fixed? I would appreciate some guidance, as I was using a bash version without any issued and now I am running into all sorts of issues with the node js version. Online I read that I need to wait for the `drain` event?

Concrete questions:

1. Should the code above now work after the commit?
2. Is the commit included in a new version already or do I need to fork/copy repo?
3. What is the *sanctionaed* way of "flushing" (for lack of a better term) my log posts?

Thanks much,

Andres

**Comment by acrodrig** [comment]
Hi. I did not get an answer to the questions above. Can you help?

**Comment by bathos** [comment]
Yes, this issue was closed by a commit that changed the behavior of `end()` so that it doesn't close the internal connection instantly, and it's live on npm.

The closest thing to a sanctioned might be to be call .end() and have a 'finish' event handler, if this is about exiting the process. When I wrote this I only had long-lived applications in mind, but there are people using it now in child processes and other situations where this is more important. I'm open to suggestions on an appropriate interface for this.

**Comment by acrodrig** [comment]
It seems to me that if log entries receives a signal that the program wants to end, it can flush all standing log dispatches and close. I do not know the internals of the library, but that is how other long-running processes could react.

I am using log entries for our web server, and some shell scripts. `le_node` is well behaved for the former and not so much for the latter.
