### ISSUE TITLE
Log level appearing as a numeric value instead of a string literal

### ISSUE THREAD

**Issue by beeman** [logentries/le_node#80]
We're using the most recent version of the `le_node` package (`v1.1.0`) and integrate it with the Bunyan logger we've set up. The configuration is similar to the one you see below.

```javascript
var bunyan = require('bunyan');
var conf = require('./conf.js');

var logger = bunyan.createLogger({
  name: 'fullcube',
  streams: []
});

if conf.get('LOGENTRIES_TOKEN') && conf.get('LOGENTRIES_LEVEL')) {
  var Logger = require('le_node');
  logger.addStream(Logger.bunyanStream({
    token: conf.get('LOGENTRIES_TOKEN'),
    minLevel: conf.get('LOGENTRIES_LEVEL')
  }));
}
```

With this configuration the entries get sent to logentries, but the value of the `level` is not what we expect. It looks like the correct (literal) value is stored in the `_level` key, and the numeric value is stored in the `level` key.

```json
{
  "name": "fullcube",
  "hostname": "local.fullcube.com",
  "pid": 92,
  "level": 20,
  "msg": "Setting up Rest API",
  "time": "2015-10-01T16:50:09.810Z",
  "v": 0,
  "_level": "debug"
}, {
  "name": "fullcube",
  "hostname": "local.fullcube.com",
  "pid": 92,
  "level": 30,
  "msg": "Updating database schemas.",
  "time": "2015-10-01T16:50:10.205Z",
  "v": 0,
  "_level": "info"
}
```

Is this expected behaviour or is it something that we can adjust by setting a configuration option somewhere?

**Comment by bathos** [comment]
This appears correct. Bunyan is the party which uses numeric values in increments of 10; they add that to every entry as "level". Logentries also tries to set a level property (that's the string), but it sees that there already is one, so it adds an underscore to prevent collision.

You can configure whether LE adds this property at all by setting the `withLevel` option to false. As for Bunyan's numeric level ID, I suspect that is also configurable, but it would be something you configure on Bunyan rather than the LE stream.

**Comment by beeman** [comment]
Thanks for you quick answer and the explanation @bathos. 

I'll check Bunyan to see if I can make it send the level as a string.
