### ISSUE TITLE
Fails to install on node 4.2.1

### ISSUE THREAD

**Issue by w4-sjcho** [logentries/le_node#82]
It seems like le_node fails to install due to dependent package dtrace-provider.

```
$ node -v
v4.2.1
$ npm install le_node

> v8flags@1.0.8 install /Users/plusaqua/tmp/le_node_test/node_modules/le_node/node_modules/gobble-cli/node_modules/v8flags
> node fetch.js

flags for v8 4.5.103.35 cached.

> dtrace-provider@0.4.0 install /Users/plusaqua/tmp/le_node_test/node_modules/le_node/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js

---------------
Building dtrace-provider failed with exit code 1 and signal 0
re-run install with environment variable V set to see the build output
---------------
le_node@1.1.1 node_modules/le_node
├── json-stringify-safe@5.0.1
├── mitm@1.1.0 (underscore@1.5.2)
├── codependency@0.1.3 (semver@2.2.1)
├── winston@1.0.0 (cycle@1.0.3, stack-trace@0.0.9, eyes@0.1.8, isstream@0.1.2, async@0.9.2, pkginfo@0.3.0, colors@1.0.3)
├── tap-spec@3.0.0 (repeat-string@1.5.2, duplexer@0.1.1, pretty-ms@1.1.0, chalk@1.0.0, tap-out@1.2.0, through2@0.6.5)
├── tape@4.0.0 (inherits@2.0.1, defined@0.0.0, resumer@0.0.0, deep-equal@1.0.0, through@2.3.7, object-inspect@1.0.0, glob@5.0.10)
├── lodash@3.9.3
├── bunyan@1.3.5 (safe-json-stringify@1.0.3, mv@2.0.3, dtrace-provider@0.4.0)
├── babel-runtime@5.4.7 (core-js@0.9.16)
├── gobble-cli@0.4.2 (ansi-regex@1.1.1, stevedore@0.1.4, cli-spinner@0.1.6, interpret@0.3.10, minimist@1.1.1, semver@4.3.6, v8flags@1.0.8, graceful-chokidar@0.1.0, chalk@0.5.1, liftoff@0.13.6, findup-sync@0.1.3, sorcery@0.2.5, prompt@0.2.14)
├── gobble@0.10.2 (require-relative@0.8.7, eventemitter2@0.4.14, buffer-crc32@0.2.5, mime@1.3.4, graceful-fs@3.0.8, rimraf@2.2.8, graceful-chokidar@0.1.0, resolve@1.1.6, debounce@1.0.0, minimatch@1.0.0, mkdirp@0.5.1, glob@4.0.6, chalk@1.0.0, sander@0.3.4, sorcery@0.6.1, promise-map-series@0.2.1, source-map-support@0.2.10, tiny-lr@0.1.5, findup-sync@0.1.3)
└── gobble-babel@5.1.0 (babel-core@5.4.7)
```

**Comment by bathos** [comment]
I couldn't replicate this locally, but the issue stems from one of Bunyan's there. Bunyan is only a dev dependency, for testing the integration. Install with `npm install --production` and most of those deps, including Bunyan, will disappear, as they are not used by le_node itself.

**Comment by w4-sjcho** [comment]
Maybe this only happens under Mac OS X 10.11 (El Capitan)

$ uname -a
Darwin SEONGui-MacBook-Pro.local 15.0.0 Darwin Kernel Version 15.0.0: Wed Aug 26 16:57:32 PDT 2015; root:xnu-3247.1.106~1/RELEASE_X86_64 x86_64

**Comment by bathos** [comment]
That could be the case, since I've heard that a lot of people have encountered issues with El Capitan's build tools, and the dtrace install has a compilation step. But perhaps it's related to [other issues](https://github.com/trentm/node-bunyan/issues/216) some people have encountered with Bunyan/dtrace on OSX even before El Capitan.

Since there's no need to perform a development install and this is really a dtrace or osx issue, I'm marking it closed. I've always thought it was somewhat odd that the default behavior of `npm install` is to do a development install. Note that in production environments the `--production` flag is usually implicit, it's only when you explicitly run `npm install` that you get the devel version of a module is considered default.
