### ISSUE TITLE
log.error

### ISSUE THREAD

**Issue by rbaindourov** [logentries/le_node#89]
Hello!

Thank you for your hard work on this SDK.
I have been using for about 2 days now, trying to integrate my nodejs app with logentries.com.

One suggestion: that the team consider creating an alias for `log.log('err'` with `log.error` to maintain parity with `console.error`.

It would just be much more intuitive, in my opinion.

[Not sure why, but log.error blows up for me.](https://github.com/logentries/le_node/issues/83)

Thanks Again.

-Robert Baindourov

**Comment by bathos** [comment]
The level names are [configurable](https://github.com/logentries/le_node#log-levels). I'm afraid we couldn't safely alias 'error' this way because we can't assume that users who *do* have a custom level name of 'error' use it for the same level number as the default 'err' level number. Although I agree 'error' is a better name, I think it wouldn't warrant a breaking change since it's simple to configure custom names.
