### ISSUE TITLE
Event to flush data in buffer

### ISSUE THREAD

**Issue by maximshe** [logentries/le_node#94]
Hi all,

Is it possible some how to force buffer flush?

In my program I need to be sure that all logs transferred to logentries, for now when program exits few last log calls are missing in logentries.

**Comment by bathos** [comment]
No -- not quite. The buffer is always flushing as fast as it can, but I think what you're asking for is a way to detect it having finished. The way to do this ought to be by calling `lenode.end()`, as with any stream, and either supplying a callback there or else listening for the `finish` event. But at present this wouldn't be guaranteed to work, either, because of incorrect assumptions I made way back about the drain event. I'll need to revisit this and come up with a better way. In the meantime -- this is awful and dirty and I'm sorry I'm suggesting it -- you could call `end()` and have a timeout (500ms is what I'd try) in the finish handler; by then it'd be clear unless you had network issues.

**Comment by maximshe** [comment]
Thank you for quick reaction and suggestions.
